name: Build

on: [ push, pull_request ]

jobs:

  build:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-11.7

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        bazel build //...
        bazel test //...
