name: Build

on: [ push, pull_request ]

jobs:

  build:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-11

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Poetry
      run: pipx install poetry

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.12'

    - uses: actions/checkout@v2

    - name: Build
      env:
        PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      run: |
        (cd ./fibonacci && poetry build && poetry run pytest)
        bazel build //...
        bazel test //...
