name: Build

on: [ push, pull_request ]

jobs:

  build:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-11.7

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Build
      env:
        PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      run: |
        bazel build //...
        bazel test //...
